# Generated by Django 5.1.4 on 2024-12-13 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_bar_address_remove_bar_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='current_occupancy',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='occupancyreport',
            name='occupancy_level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
