# Generated by Django 5.1.4 on 2024-12-13 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bar_current_occupancy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupancyreport',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.bar'),
        ),
    ]
