# Generated by Django 5.1.4 on 2024-12-14 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bar_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupancyreport',
            name='line_wait',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
