# Generated by Django 5.1.4 on 2024-12-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_occupancyreport_line_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='current_line',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
