# Generated by Django 5.1.4 on 2024-12-14 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_bar_current_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bar',
            old_name='current_line',
            new_name='displayed_current_line',
        ),
    ]
