# Generated by Django 5.1.4 on 2024-12-14 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_current_line_bar_displayed_current_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bar',
            old_name='current_occupancy',
            new_name='displayed_current_occupancy',
        ),
    ]
