# Generated by Django 5.1.4 on 2025-01-08 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_occupancyreport_flagged_occupancyreport_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupancyreport',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='occupancyreport',
            name='longitude',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
