# Generated by Django 5.1.4 on 2025-01-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_occupancyreport_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='users_nearby',
            field=models.IntegerField(default=0),
        ),
    ]
