# Generated by Django 5.1.4 on 2025-02-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_near_bar',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='occupancyreport',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
