# Generated by Django 5.1.4 on 2025-03-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_userprofile_last_updated_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_near_bar',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
