# Generated by Django 5.1.4 on 2025-03-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_userprofile_strikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_near_bar',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='strikes',
            field=models.IntegerField(default=0),
        ),
    ]
