# Generated by Django 5.1.4 on 2025-03-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_userprofile_is_near_bar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(null=True)),
                ('is_clear', models.BooleanField(default=False)),
                ('is_clouds', models.BooleanField(default=False)),
                ('is_rain', models.BooleanField(default=False)),
                ('is_snow', models.BooleanField(default=False)),
                ('is_thunderstorm', models.BooleanField(default=False)),
                ('is_drizzle', models.BooleanField(default=False)),
                ('is_mist', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='occupancyreport',
            name='closed_event',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='occupancyreport',
            name='sunrise',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occupancyreport',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occupancyreport',
            name='weather',
            field=models.CharField(blank=True, null=True),
        ),
    ]
