# Generated by Django 5.1.4 on 2025-03-19 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_currentweather_weather_string'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentweather',
            old_name='is_clear',
            new_name='clear',
        ),
        migrations.RenameField(
            model_name='currentweather',
            old_name='is_clouds',
            new_name='clouds',
        ),
        migrations.RenameField(
            model_name='currentweather',
            old_name='is_drizzle',
            new_name='drizzle',
        ),
        migrations.RenameField(
            model_name='currentweather',
            old_name='is_mist',
            new_name='mist',
        ),
        migrations.RenameField(
            model_name='currentweather',
            old_name='is_rain',
            new_name='rain',
        ),
        migrations.RenameField(
            model_name='currentweather',
            old_name='is_snow',
            new_name='snow',
        ),
        migrations.RenameField(
            model_name='currentweather',
            old_name='is_thunderstorm',
            new_name='thunderstorm',
        ),
    ]
